apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: testing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: www.lb.com
    http:
      paths:
      - path: /
        backend:
          serviceName: svc-tomcat
          servicePort: 80
